---
title: "6th EFSPI regulatory statistics workshop: analysis"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl", "tidyverse")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- paste(getwd(), "/", sep = "")

# number of days
d <- 3

res <- NULL

for (i in 1:d){
  dialin <- as.data.frame(read_excel(paste(path, "data/2021/dialin_session", i, ".xlsx", sep = "")))
  dialin$time <- as.numeric(dialin[, "Time in Session (minutes)"])
  
  # sum time in session per participant
  res[[i]] <- dialin %>% group_by(Email) %>% summarise(sum_time = sum(time, na.rm = TRUE)) %>% arrange(desc(sum_time))
}

# print(as_tibble(res[[1]]), n = 100)
trafo <- function(x, dur = 180){return(pmin(pull(x, 2) / dur, 1, na.rm = TRUE))}

cs <- c(0, 60, 120, 150, Inf)
labs <- paste("stayed > ", cs[1:(length(cs) - 1)], " minutes", sep = "")
labs[1] <- "stayed <= 60 minutes"
stay <- pull(res[[1]], 2)
for (j in 2:d){stay <- c(stay, pull(res[[j]], 2))}
dat <- data.frame("session" = paste("Webinar ", rep(1:d, times = unlist(lapply(lapply(res, pull, 2), length))), sep = ""), "stay" = stay, 
                        "stay_cut" = cut(stay, breaks = cs, labels = labs, 
                                         include.lowest = TRUE, ordered.result = TRUE))
```

# Introduction

This short document summarizes some analyses of the 6th EFSPI regulatory statistics workshop in Basel 12/13th October 2020. 

# Number of participants dialing in for a given proportion of entire webinar

```{r, echo = FALSE, fig.cap = "Number of patients staying for an at least proportion of time of a given webinar.", fig.align = "center", fig.width = 9, fig.height = 5}
par(las = 1)
boxplot(list(trafo(res[[1]]), trafo(res[[2]]), trafo(res[[3]], 240)), names = paste("Session ", 1:d, sep = ""), ylab = "length of stay as proportion of total webinar duration (180 or 240 minutes)")
```

As an illustrative reading example in Webinar 1 quite precisely half of participants stayed for at least 80\% of the 180 minutes that the webinar lasted.

```{r, echo = FALSE, fig.cap = "Number of patients staying for an at least proportion of time of a given webinar.", fig.align = "center", fig.width = 9, fig.height = 8}
par(las = 1)
barplot(table(dat[, 3], dat[, 1])[, 1:2], beside = TRUE, ylab = "number of participants", legend.text = levels(dat[, 3]))

cs2 <- c(0, 60, 120, 150, 180, Inf)
labs2 <- paste("stayed > ", cs2[1:(length(cs2) - 1)], " minutes", sep = "")
labs2[1] <- "stayed <= 60 minutes"
cut2 <- cut(stay, breaks = cs2, labels = labs2, include.lowest = TRUE, ordered.result = TRUE)
par(las = 2, mar = c(10, 3, 1, 1))
barplot(table(cut2), beside = TRUE, ylab = "number of participants", names = levels(cut2))
title("Webinar 3")
```


